### ISSUE TITLE
chips for predefined timers should be show after the first timer startet

### ISSUE THREAD

**Issue by mlangguth** [eyalgal/simple-timer-card#65]
Is there a chance that predefined timers (timer_presets) can still be shown after the first timer ist started?
Would be realy nice for let's say starting mulitple 6min-Timers for tee in the kitchen, some time after another (multiple running 6min-timers)

<img width="848" height="678" alt="Image" src="https://github.com/user-attachments/assets/9187e7b2-13d9-46e4-afc6-71aa6a6b2f34" />

**Comment by eyalgal** [comment]
Fixed in [v1.5.1](https://github.com/eyalgal/simple-timer-card/releases/tag/v1.5.1).

**Comment by mlangguth** [comment]
as like #69: Still the same:
<img width="663" height="507" alt="Image" src="https://github.com/user-attachments/assets/58457f82-1afb-4d94-839b-7ae58bb3dd57" />
